[package]
name = "samdebug-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
lzma-rs.workspace = true
samdebug-core = { version = "=0.1.0", path = "../samdebug-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
